# Generated by Django 4.0.6 on 2022-08-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=120, verbose_name='Nombres y Apellidos')),
                ('dni', models.CharField(max_length=8, verbose_name='Número de DNI')),
                ('telefono', models.CharField(max_length=100, verbose_name='Teléfono')),
                ('correo_electronico', models.CharField(max_length=200, verbose_name='Email')),
            ],
        ),
    ]
