# Generated by Django 4.0.6 on 2022-08-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.CharField(default=' ', max_length=10, verbose_name='Curso'),
            preserve_default=False,
        ),
    ]
